import {siteHeader} from './site-nav.mjs';

export function renderTrain(req,res){
 const email=req.user?.email||'';
 res.set('Cache-Control','private, no-store').type('html').send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Train · Catan field guide</title><link rel="stylesheet" href="/dashboard-assets/site-nav.css"><style>
:root{color-scheme:light;background:#faf9f6;color:#252522;font:14px/1.55 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,sans-serif}*{box-sizing:border-box}body{margin:0}main{max-width:860px;margin:0 auto;padding:40px 24px 80px}h1{font-size:30px;line-height:1.15;letter-spacing:-.8px;margin:0 0 8px}p{margin:0}.lede{color:#66645d;max-width:650px}.tracks{display:grid;gap:0;margin:30px 0}.track{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px 24px;align-items:center;padding:22px 0;border-top:1px solid #dedcd5}.track:last-child{border-bottom:1px solid #dedcd5}.track h2{font-size:18px;letter-spacing:-.2px;margin:0 0 4px}.track p{color:#66645d;max-width:560px}.track a{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:9px 16px;border:1px solid #252522;border-radius:5px;color:#252522;text-decoration:none;white-space:nowrap;font-weight:650}.track a:hover{background:#252522;color:white}.track a:focus-visible,.reference a:focus-visible{outline:2px solid #526477;outline-offset:3px}.reference{color:#66645d;font-size:13px}.reference a{color:#252522;text-decoration:underline;text-underline-offset:3px}@media(max-width:600px){main{padding:28px 18px 60px}h1{font-size:26px}.track{grid-template-columns:1fr;padding:18px 0}.track a{justify-self:start}}
</style></head><body>${siteHeader({active:'train',email})}<main id="main"><h1>Train a decision</h1><p class="lede">Pick the skill you want to practice. Each exercise keeps its own progress where you use it.</p><div class="tracks">
<section class="track"><div><h2>Math flashcards</h2><p>Recall dice, resource production, build costs and trade arithmetic. Reviews return when due.</p></div><a href="/flashcards">Review cards</a></section>
<section class="track"><div><h2>Odds and timing</h2><p>Judge correlated production, deadlines, opportunity costs and conditional forecasts in short exercises.</p></div><a href="/#practice-odds">Start odds drill</a></section>
<section class="track"><div><h2>Opponent memory and forecasts</h2><p>Track public evidence, test what a hand could contain, then make and score a dated forecast.</p></div><a href="/#opponents-forecast">Open forecasts</a></section>
<section class="track"><div><h2>Decision practice</h2><p>Choose a recorded match, commit your move and reasoning, then compare plausible outcomes.</p></div><a href="/history">Choose a match</a></section>
</div><p class="reference">Need the rules first? <a href="/#reference">Open the math reference</a>.</p></main></body></html>`);
}
