import test from 'node:test';
import assert from 'node:assert/strict';
import {createClient} from '@supabase/supabase-js';
import {DashboardStore} from '../lib/dashboard-store.mjs';
test('live dashboard RLS, revision conflicts and show RPC',{skip:!process.env.TEST_SUPABASE_SECRET_KEY},async()=>{
 const admin=createClient(process.env.SUPABASE_URL,process.env.TEST_SUPABASE_SECRET_KEY,{auth:{persistSession:false}}),ids=[];
 async function user(i){const email=`catan-dash-test-${Date.now()}-${i}@example.com`;const u=await admin.auth.admin.createUser({email,email_confirm:true});assert.ifError(u.error);ids.push(u.data.user.id);const l=await admin.auth.admin.generateLink({type:'magiclink',email});assert.ifError(l.error);const db=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false}});assert.ifError((await db.auth.verifyOtp({email,token:l.data.properties.email_otp,type:'email'})).error);return {db,store:new DashboardStore({db,userId:u.data.user.id,actor:'agent'})};}
 try{const a=await user('a'),b=await user('b');let p=await a.store.createStarterPage();assert.equal(p.components.length,5);assert.equal((await a.store.listPages()).length,1);assert.equal((await b.store.listPages()).length,0);await assert.rejects(()=>b.store.getPage(p.id),e=>e.code==='not_found');const results=await Promise.allSettled([a.store.updatePage(p.id,{expectedRevision:p.revision,title:'One'}),a.store.updatePage(p.id,{expectedRevision:p.revision,title:'Two'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected'&&r.reason.code==='conflict').length,1);const show=await a.store.show(p.id,p.components[0].id);assert.equal(show.seq,1);assert.equal((await a.store.show(p.id)).seq,2);const theft=await b.db.from('dashboard_pages').update({title:'Stolen'}).eq('id',p.id).select();assert.ifError(theft.error);assert.deepEqual(theft.data,[]);const overwrite=await a.db.from('dashboard_pages').update({user_id:ids[1]}).eq('id',p.id);assert(overwrite.error);await a.store.deletePage(p.id,{});assert.equal((await a.store.listPages()).length,0);await a.store.restorePage(p.id);assert.equal((await a.store.listPages()).length,1);console.log('Live dashboard isolation, CAS, archive/restore and show verified.');}
 finally{for(const id of ids)assert.ifError((await admin.auth.admin.deleteUser(id)).error);}
});
