import test from 'node:test';
import assert from 'node:assert/strict';
import {createClient} from '@supabase/supabase-js';
import {GameStore} from '../lib/game-store.mjs';
test('live game atomic moves, seat isolation, observer replay and revocation',{skip:!process.env.TEST_SUPABASE_SECRET_KEY},async()=>{
 const db=createClient(process.env.SUPABASE_URL,process.env.TEST_SUPABASE_SECRET_KEY,{auth:{persistSession:false}}),store=new GameStore(db);let uid;
 try{const u=await db.auth.admin.createUser({email:`catan-game-test-${Date.now()}@example.com`,email_confirm:true});assert.ifError(u.error);uid=u.data.user.id;let row=await store.create(uid);const own=await store.present(row,0,true);assert.equal(own.view.mySeat,0);assert(!('rng' in own.view));assert(!('devDeck' in own.view));for(const p of own.view.players.filter(p=>p.seat!==0))assert(!('resources' in p));const conn=await store.connection(row,1),obs=await store.observerConnection(row);assert.equal((await store.authenticate(conn.token)).seat,1);assert.equal(await store.authenticate(obs.token),null);assert.equal(await store.authenticateObserver(conn.token),null);assert.equal((await store.authenticateObserver(obs.token)).seat,0);await assert.rejects(()=>store.owned(row.id,'00000000-0000-0000-0000-000000000000'),e=>e.status===404);
 const seat=row.state.current,view=await store.present(row,seat);const action=view.view.legalActions.actions.find(a=>a.type==='build_settlement');assert(action);const attempts=await Promise.allSettled([store.act(row,seat,row.revision,action),store.act(row,seat,row.revision,action)]);assert.equal(attempts.filter(a=>a.status==='fulfilled').length,1);assert.equal(attempts.filter(a=>a.status==='rejected'&&a.reason.status===409).length,1);row=attempts.find(a=>a.status==='fulfilled').value.row;const events=await store.events(row,0);assert.equal(events.events.length,1);assert.equal(events.events[0].id,row.revision);assert.equal((await store.events(row,events.cursor)).events.length,0);assert(!JSON.stringify(events).includes('devDeck'));const rotated=await store.connection(row,1);assert.equal(await store.authenticate(conn.token),null);assert(await store.authenticate(rotated.token));await store.revoke(row,1);assert.equal(await store.authenticate(rotated.token),null);await store.revokeObserver(row);assert.equal(await store.authenticateObserver(obs.token),null);await store.archive(row);await assert.rejects(()=>store.owned(row.id,uid));console.log('Game seats, readonly credentials, atomic event replay and revocation verified.');
 }finally{if(uid)assert.ifError((await db.auth.admin.deleteUser(uid)).error);}
});
