(function(global){
'use strict';
const resourceNames=['Wood','Brick','Sheep','Wheat','Ore'];
const emptyOpponent=(i)=>({name:['Red','Blue','Orange'][i],total:null,known:[0,0,0,0,0],guess:[0,0,0,0,0],guessReason:'',engine:'Unclassified',production:'',prod:['','','','',''],action:'City',move:'',when:'Next own turn',confidence:'Medium',evidence:'',condition:'',alternative:'',falsifier:'',response:'',events:[]});
const num=v=>Math.max(0,Math.min(80,Math.floor(Number(v)||0)));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=p=>{if(p===0)return '0%';if(p===1)return '100%';const n=p*100;if(n<.01)return '<0.01%';if(n>99.99)return '>99.99%';return `${n.toFixed(n<1?2:n<10?1:0)}%`;};
const brier=v=>v>0&&v<.0001?'<0.0001':v.toFixed(4);
function sanitize(raw){const data={selected:0,people:[0,1,2].map(emptyOpponent),predictions:[],forecasts:[]};if(!raw||typeof raw!=='object')return data;data.selected=Math.max(0,Math.min(2,num(raw.selected)));for(let i=0;i<3;i++){const src=raw.people?.[i];if(!src)continue;const p=data.people[i];for(const key of Object.keys(p)){if(key==='total')p.total=src.total==null||src.total===''?null:num(src.total);else if(key==='known'||key==='guess'){if(Array.isArray(src[key])&&src[key].length===5)p[key]=src[key].map(num);}else if(key==='prod'){if(Array.isArray(src.prod)&&src.prod.length===5)p.prod=src.prod.map(x=>String(x||'').slice(0,80));}else if(key==='events'){if(Array.isArray(src.events))p.events=src.events.filter(e=>typeof e==='string').map(e=>e.slice(0,220));}else if(typeof src[key]==='string')p[key]=src[key].slice(0,key==='name'?24:500);}}if(Array.isArray(raw.predictions))data.predictions=raw.predictions.filter(p=>p&&typeof p.text==='string').map(p=>({text:p.text.slice(0,1800),name:String(p.name||'Opponent').slice(0,24),at:String(p.at||'').slice(0,40),outcome:['pending','yes','no','unclear'].includes(p.outcome)?p.outcome:'pending'}));if(global.CatanForecast)data.forecasts=global.CatanForecast.sanitizeForecasts(raw.forecasts);else if(Array.isArray(raw.forecasts))data.forecasts=raw.forecasts;return data;}
function knowledge(p){const known=p.known.reduce((a,b)=>a+b,0),guessed=p.guess.reduce((a,b)=>a+b,0);if(p.total===null)return {valid:false,reason:'Enter their observed hand size.'};if(known>p.total)return {valid:false,reason:'Known cards exceed the observed hand size.'};const unknown=p.total-known;if(guessed>unknown)return {valid:false,reason:'Guesses exceed the unknown cards. Adjust the guess or the known counts.'};return {valid:true,unknown,guessed,unassigned:unknown-guessed};}
function possible(p,cost){const k=knowledge(p);if(!k.valid)return 'unrecorded';const need=cost.reduce((s,c,i)=>s+Math.max(0,c-p.known[i]),0);return need===0?'yes':need<=k.unknown?'maybe':'no';}
function applyEvent(p,event,costs){const k=knowledge({...p,guess:[0,0,0,0,0]});if(!k.valid)throw Error(k.reason);const next=JSON.parse(JSON.stringify(p)),q=num(event.q)||1;let delta=[0,0,0,0,0],label='';if(event.type==='gain'){delta[event.resource]=q;label=`Saw +${q} ${resourceNames[event.resource].toLowerCase()}`;}else if(event.type==='pay'){delta[event.resource]=-q;label=`Saw −${q} ${resourceNames[event.resource].toLowerCase()}`;}else if(costs[event.type]){delta=costs[event.type].map(v=>-v);label=`Paid for ${event.type.toLowerCase()}`;}else if(event.type==='hidden-loss'){if(q>p.total)throw Error('Cannot lose more cards than the recorded hand size.');next.total-=q;next.known=next.known.map(v=>Math.max(0,v-q));label=`Lost ${q} unseen card${q===1?'':'s'}; guaranteed counts weakened`;}else if(event.type==='hidden-gain'){next.total+=q;label=`Gained ${q} unseen card${q===1?'':'s'}`;}else throw Error('Choose an event.');
 if(delta.some(v=>v)){const extraNeeded=delta.reduce((s,v,i)=>s+Math.max(0,-v-p.known[i]),0);if(extraNeeded>k.unknown)throw Error('This payment contradicts the recorded counts. Correct the record first.');next.known=next.known.map((v,i)=>Math.max(0,v+delta[i]));next.total+=delta.reduce((a,b)=>a+b,0);}
 next.guess=[0,0,0,0,0];next.events=[...next.events,label+' · revise guesses'].slice(-8);return next;}
function init({root,initial,onSave,onForecastCreate,onForecastResolve,onForecastLocal}){
const M=global.CatanMath,F=global.CatanForecast,host=root.querySelector('#opponents-ui');let data=sanitize(initial),covered=false,form={event:'gain',resource:'0',quantity:'1'},done='';const $=id=>host.querySelector('#'+id);const save=()=>onSave(JSON.parse(JSON.stringify(data)));
const opts=(items,value)=>items.map(x=>`<option value="${esc(x)}"${x===value?' selected':''}>${esc(x)}</option>`).join('');
const events=[['gain','Received resource'],['pay','Paid resource'],['hidden-loss','Lost unseen card'],['hidden-gain','Gained unseen card'],['Road','Built a road'],['Settlement','Built a settlement'],['City','Upgraded to a city'],['Development card','Bought a dev card']];
const numberInput=(attrs,value,label)=>`<input ${attrs} type="number" inputmode="numeric" min="0" max="80" value="${value}" aria-label="${label}">`;
// One column template for facts, estimates and recall, so each resource sits in the same place in all three.
const head=(sel,hand,end)=>`<div class="op-row op-head" aria-hidden="true"><span class="op-c-sel">${sel}</span><span class="op-c-name">Opponent</span><span class="op-c-hand">${hand}</span>${resourceNames.map((r,j)=>`<span class="op-c-r${j+1}"><span class="cl-swatch" style="background:var(--cl-r${j+1})"></span>${r}</span>`).join('')}<span class="op-c-end">${end}</span></div>`;
const factsRow=(p,i)=>`<div class="op-row${i===data.selected?' op-on':''}"><span class="op-c-sel"><button class="op-pick" data-analyze="${i}" aria-pressed="${i===data.selected}" aria-label="Analyze ${esc(p.name)}"></button></span><span class="op-c-name"><input data-person="${i}" data-field="name" value="${esc(p.name)}" maxlength="24" aria-label="Opponent ${i+1} name"></span><span class="op-c-hand">${numberInput(`data-person="${i}" data-field="total"`,p.total??'',esc(p.name)+' observed hand size')}</span>${resourceNames.map((r,j)=>`<span class="op-c-r${j+1}">${numberInput(`data-person="${i}" data-kind="known" data-resource="${j}"`,p.known[j],esc(p.name)+' known '+r)}</span>`).join('')}<span class="op-c-end op-num" id="opp-unknown-${i}"></span><div class="op-c-sub" id="opp-capabilities-${i}"></div></div>`;
const guessRow=(p,i)=>`<div class="op-row"><span class="op-c-sel"></span><span class="op-c-name" data-name-label="${i}">${esc(p.name)}</span><span class="op-c-hand op-num" id="opp-pool-${i}"></span>${resourceNames.map((r,j)=>`<span class="op-c-r${j+1}">${numberInput(`class="op-est" data-person="${i}" data-kind="guess" data-resource="${j}"`,p.guess[j],esc(p.name)+' guessed '+r)}</span>`).join('')}<span class="op-c-end" id="opp-status-${i}" aria-live="polite"></span><div class="op-c-sub"><input data-person="${i}" data-field="guessReason" value="${esc(p.guessReason)}" maxlength="500" placeholder="Why? e.g. saw ore income, no ore spent since" aria-label="${esc(p.name)}: why this guess"></div></div>`;
const recallRow=(p,i)=>`<div class="op-row"><span class="op-c-sel"></span><span class="op-c-name" data-name-label="${i}">${esc(p.name)}</span><span class="op-c-hand"><input id="opp-recall-${i}-5" type="number" inputmode="numeric" min="0" max="80" aria-label="Recall ${esc(p.name)} total"></span>${resourceNames.map((r,j)=>`<span class="op-c-r${j+1}"><input id="opp-recall-${i}-${j}" type="number" inputmode="numeric" min="0" max="80" aria-label="Recall ${esc(p.name)} ${r}"></span>`).join('')}<span class="op-c-end op-num" id="opp-recall-score-${i}"></span></div>`;
function render(){
 const selected=data.people[data.selected],openMore=Boolean(selected.condition||selected.alternative||selected.response);
 host.innerHTML=`<div class="op-top"><div><h2>Opponents</h2><p class="op-lede">Record what you saw. Estimate the rest separately. Commit to a prediction before they move.</p></div><button class="cl-button" id="opp-cover" aria-pressed="${covered}">${covered?'Show records':'Hide records and recall'}</button></div>
 <div id="opp-records" ${covered?'hidden':''}>
 <section class="op-block" aria-labelledby="op-facts-title"><div class="op-block-head"><h3 id="op-facts-title">Facts</h3><span class="op-kind">Seen at the table</span></div><p class="op-caption">Known counts are guaranteed minimums. Unknown = hand size − known.</p>
 <div class="op-grid op-facts">${head('Read','Hand','Unknown')}${data.people.map(factsRow).join('')}</div>
 <div id="opp-observation-section" class="op-event"><h4>Record a public event</h4><div class="op-event-form"><label>Opponent<select id="opp-selected">${data.people.map((p,i)=>`<option value="${i}" ${i===data.selected?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label class="op-wide">Event<select id="opp-event">${events.map(([v,l])=>`<option value="${v}"${v===form.event?' selected':''}>${l}</option>`).join('')}</select></label><label>Resource<select id="opp-resource">${resourceNames.map((r,i)=>`<option value="${i}"${String(i)===form.resource?' selected':''}>${r}</option>`).join('')}</select></label><label class="op-narrow">Cards<input id="opp-quantity" type="number" inputmode="numeric" min="1" max="30" value="${esc(form.quantity)}"></label><button id="opp-apply" class="cl-button op-primary">Record</button></div>
 <div id="opp-event-error" role="alert" class="cl-warn op-msg"></div><div id="opp-event-done" class="op-msg op-done" aria-live="polite">${esc(done)}</div>
 <p class="op-caption">Builds deduct their recipe. Unseen gains and losses change only the hand size; a loss lowers every guaranteed count. Any event clears that opponent’s estimate, so an old guess never becomes a fact.</p>
 <details><summary>Recent events · <span id="opp-event-person"></span></summary><ol id="opp-event-log"></ol></details></div></section>
 <section class="op-block" aria-labelledby="op-est-title"><div class="op-block-head"><h3 id="op-est-title">Estimates</h3><span class="op-kind">Your guess, not fact</span></div><p class="op-caption">Split each opponent’s unknown cards by type. Leave cards unassigned when unsure.</p>
 <div class="op-grid op-guesses">${head('','Unknown','')}${data.people.map(guessRow).join('')}</div>
 <details><summary>What these numbers can and can’t tell you</summary><p class="op-caption">Guaranteed and possible purchases use only the recorded facts: before trades and without checking board legality. Guesses are one subjective allocation. The page keeps no history of which cards were likely together.</p></details></section>
 <section class="op-block op-forecast" aria-labelledby="op-forecast-title"><div class="op-block-head"><h3 id="op-forecast-title">Your numerical forecast</h3><span class="op-kind">Saved before the move</span></div>
 <p class="op-caption">Define what happens by the deadline. For a build, capability means holding the recipe by then; choice means choosing this event <strong>given capability</strong>. Board access and the legal build turn still matter.</p>
 <div class="op-prod"><h4>Assumed model for ${esc(selected.name)}</h4><p class="op-caption">Enter observed production numbers for each resource, e.g. 6 9x2 for one 6 settlement and a 9 city. Update after builds and robber moves.</p><div class="op-prod-fields">${resourceNames.map((r,i)=>`<label>${r}<input data-prod="${i}" value="${esc(selected.prod[i])}" placeholder="6 9x2" maxlength="80"></label>`).join('')}</div><p id="op-model-reading" class="op-caption" aria-live="polite"></p></div>
 <div class="op-forecast-form"><label>Event<select id="op-f-event">${F.EVENTS.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label><label>Within their next turns<input id="op-f-turns" type="number" min="1" max="5" value="1"></label><label>Approx. table rolls<input id="op-f-rolls" type="number" min="1" max="40" value="4"></label><label class="op-f-wide">Exact event or location<input id="op-f-detail" maxlength="300" placeholder="City at the ore site; count any city if unspecified"></label><label>Able to do it by deadline (%)<input id="op-f-afford" type="number" min="0" max="100" value="50"></label><label>Chooses it if able (%)<input id="op-f-choose" type="number" min="0" max="100" value="50"></label><label class="op-f-wide">Evidence and assumptions<textarea id="op-f-evidence" rows="2" maxlength="500" placeholder="Known cards, likely trades, alternative purchases, legal site"></textarea></label></div>
 <p id="op-f-combined" class="op-f-combined">Forecast: 25% chance of the event by the deadline.</p><button id="op-f-save" class="cl-button op-primary">Save forecast</button><p id="op-f-error" role="alert" class="cl-warn"></p>
 <details class="op-log"><summary>Forecasts and calibration · <span id="op-f-summary"></span></summary><div id="op-f-log"></div></details></section>
 <section class="op-block" aria-labelledby="opp-thesis-heading"><div class="op-block-head"><h3 id="opp-thesis-heading">Written next-move prediction</h3><span class="op-kind">Your qualitative hypothesis</span></div>
 <div class="op-read"><div class="op-read-engine"><h4>What they are building</h4><label>Engine<select data-strategy="engine">${opts(['Unclassified',...global.CatanPracticeModel.categories],selected.engine)}</select></label><label>Production and ports<input data-strategy="production" value="${esc(selected.production)}" maxlength="500" placeholder="6 ore ×2; 9 wheat ×1; sheep port; no brick"></label><p class="op-caption">List what each number pays them; a city on 6 ore pays 2 ore per 6. Update after builds and robber moves.</p><label>Likely next purchase<select data-strategy="action">${opts(Object.keys(M.costs),selected.action)}</select></label><div id="opp-missing" class="op-missing"></div></div>
 <div class="op-read-predict"><h4>Next-move prediction</h4><div class="op-pair"><label class="op-grow"><span>Exact move and location <small>required</small></span><input data-strategy="move" maxlength="500" value="${esc(selected.move)}" placeholder="Road from east fork toward the 9-wheat harbor"></label></div><div class="op-pair"><label>By when<select data-strategy="when">${opts(['Next own turn','Within 2 own turns','Within 3 own turns','After a specific roll / trade'],selected.when)}</select></label><label>Confidence<select data-strategy="confidence">${opts(['Low','Medium','High'],selected.confidence)}</select></label></div>
 <label><span>Evidence you saw <small>required</small></span><textarea data-strategy="evidence" rows="2" maxlength="500" placeholder="Two wood receipts; kept brick; last road points east">${esc(selected.evidence)}</textarea></label><label><span>What would change your mind <small>required</small></span><textarea data-strategy="falsifier" rows="2" maxlength="500" placeholder="They spend brick elsewhere, or build a city first">${esc(selected.falsifier)}</textarea></label>
 <details id="opp-more"${openMore?' open':''}><summary>Trigger, fallback and your response</summary><label>Prerequisite or trigger<textarea data-strategy="condition" rows="2" maxlength="500" placeholder="If they get 1 wheat or trade for it before Blue blocks the site">${esc(selected.condition)}</textarea></label><label>Their alternative if it fails<textarea data-strategy="alternative" rows="2" maxlength="500" placeholder="Buy a dev card instead; delay expansion">${esc(selected.alternative)}</textarea></label><label>Your response if you’re right<input data-strategy="response" value="${esc(selected.response)}" maxlength="500" placeholder="Don’t trade them wheat; consider taking the site first"></label></details></div></div>
 <div class="op-commit"><div class="op-commit-label">Prediction as it will be saved</div><div id="opp-thesis" class="op-thesis"></div><div class="op-commit-actions"><button id="opp-predict" class="cl-button op-primary">Save prediction</button><div id="opp-predict-error" class="op-msg" role="alert"></div></div></div></section></div>
 <section id="opp-recall" class="op-block" aria-labelledby="op-recall-title" ${covered?'':'hidden'}><div class="op-block-head"><h3 id="op-recall-title">Recall</h3><span class="op-kind">Facts only are scored</span></div><p class="op-caption">Enter each opponent’s hand size and the guaranteed counts you recorded.</p>
 <div class="op-grid op-recall">${head('','Hand','Score')}${data.people.map(recallRow).join('')}</div>
 <label class="op-infer"><span>Your estimates and predictions, from memory <small>not scored</small></span><textarea rows="3" placeholder="Red: probably 2 ore; expects a city after wheat. Evidence…"></textarea></label><button class="cl-button op-primary" id="opp-check-recall">Check recall</button><div id="opp-recall-result" aria-live="polite"></div></section>
 <details class="op-log"><summary>Prediction log · <span id="opp-log-summary"></span></summary><div id="opp-prediction-log"></div></details>`;
 bind();refresh();renderPredictions();renderForecasts();modelReading();combined();syncEventForm();
}
function refresh(){for(let i=0;i<3;i++){const p=data.people[i],k=knowledge(p),facts=knowledge({...p,guess:[0,0,0,0,0]});$('opp-selected').options[i].textContent=p.name;host.querySelector('[data-analyze="'+i+'"]').setAttribute('aria-label','Analyze '+p.name);host.querySelectorAll('[data-name-label="'+i+'"]').forEach(el=>el.textContent=p.name);host.querySelectorAll('[data-person="'+i+'"]').forEach(input=>{if(input.dataset.kind)input.setAttribute('aria-label',p.name+' '+(input.dataset.kind==='known'?'known':'guessed')+' '+resourceNames[+input.dataset.resource]);else if(input.dataset.field==='total')input.setAttribute('aria-label',p.name+' observed hand size');});
 $('opp-unknown-'+i).textContent=facts.valid?facts.unknown:'—';$('opp-pool-'+i).textContent=facts.valid?facts.unknown:'—';
 $('opp-capabilities-'+i).innerHTML=facts.valid?`<span class="op-cap-lead">From facts:</span> ${Object.entries(M.costs).map(([name,cost])=>{const s=possible(p,cost);return `<span class="op-cap op-cap-${s}">${esc(name==='Development card'?'Dev card':name)} ${({yes:'<strong>guaranteed</strong>',maybe:'possible',no:'ruled out',unrecorded:'—'})[s]}</span>`;}).join('<span class="op-dot"> · </span>')}`:`<span class="cl-warn">${esc(facts.reason)}</span>`;
 const status=$('opp-status-'+i);status.textContent=!facts.valid?'Fix facts first':!k.valid?`${k.guessed-facts.unknown} too many`:k.unassigned?`${k.unassigned} unassigned`:'All assigned';status.classList.toggle('cl-warn',!k.valid);}
 const p=data.people[data.selected],k=knowledge(p),cost=M.costs[p.action]||M.costs.City,estimate=p.known.map((v,i)=>v+p.guess[i]);$('opp-event-person').textContent=p.name;$('opp-thesis-heading').textContent=`Written prediction: ${p.name}`;$('opp-event-log').innerHTML=p.events.map(e=>`<li>${esc(e)}</li>`).join('')||'<li>No recorded events.</li>';
 const missing=cost.map((c,i)=>Math.max(0,c-estimate[i])),label=missing.map((v,i)=>v?`${v} ${resourceNames[i].toLowerCase()}`:'').filter(Boolean).join(' + ');$('opp-missing').textContent=k.valid?(label?`Under your current guess: short ${label} for ${p.action.toLowerCase()}${k.unassigned?`; ${k.unassigned} cards remain unassigned`:''}.`:`Your known + guessed cards pay for ${p.action.toLowerCase()}; guesses are not confirmed.`):'Record their hand to compare a purchase against it.';
 $('opp-thesis').textContent=`${p.name}: ${p.engine}. ${p.move?`I expect ${p.move}`:'Name a specific move and location'}, ${p.when.toLowerCase()} (${p.confidence.toLowerCase()} confidence). Evidence: ${p.evidence||'not yet recorded'}. Requires: ${p.condition||'state the resource or board prerequisite'}. Alternative: ${p.alternative||'not yet recorded'}. Reconsider if: ${p.falsifier||'not yet recorded'}. My response: ${p.response||'not yet recorded'}.`;
}
function syncEventForm(){const kind=$('opp-event').value;$('opp-resource').disabled=!['gain','pay'].includes(kind);$('opp-quantity').disabled=Boolean(M.costs[kind]);}
function modelReading(){
 const p=data.people[data.selected],read=$('op-model-reading'),parsed=F.parseProduction(p.prod),k=knowledge({...p,guess:[0,0,0,0,0]});
 if(parsed.errors.length){read.textContent=parsed.errors.join(' · ');return null;}
 if(!k.valid){read.textContent=k.reason;return null;}
 const event=$('op-f-event').value,cost=F.COSTS[event];
 if(!cost){read.textContent='For a custom event, describe capability and choice yourself.';return null;}
 const range=F.handRange(p.known,p.total),rangeText=`Plausible hands: ${range.count} combinations, each resource ranges ${resourceNames.map((r,i)=>`${r} ${range.min[i]}–${range.max[i]}`).join(' · ')}. The separate maxima cannot all occur in one hand.`;
 if(k.unknown>8){read.textContent=rangeText+' More than 8 unknown cards: the exact prior calculation is withheld to keep this page responsive.';return null;}
 const odds=F.affordOdds(p.known,p.total,cost,parsed.pips),base=rangeText+` Already able to pay: ${pct(odds.equalHands)} if each hand composition is equally likely; ${pct(odds.cardWeights)} if unseen cards independently follow production weights${parsed.empty?' (equal weights used because no production was entered)':''}. These are stated priors, not learned odds.`;
 const rolls=Number($('op-f-rolls').value);
 if(rolls>12||!Number.isInteger(rolls)||rolls<1){read.textContent=base+' Set a horizon of 1–12 rolls for the exact no-trade deadline estimate.';return null;}
 const result=F.capability({known:p.known,total:p.total,cost,payouts:parsed.payouts,weights:parsed.pips,rolls});
 read.textContent=base+` With no trades, robber, discards or other spending: ${pct(result.atDeadline)} can first afford the recipe within ${rolls} table rolls. This does not establish a legal build turn or choice.`;
 return {pAffordNoTrade:result.atDeadline,assumption:'Unknown cards independently follow production weights; no trades, robber, discards or spending',rolls};
}
function combined(){const a=Number($('op-f-afford').value),c=Number($('op-f-choose').value);$('op-f-combined').textContent=$('op-f-afford').value!==''&&$('op-f-choose').value!==''&&Number.isFinite(a)&&Number.isFinite(c)&&a>=0&&a<=100&&c>=0&&c<=100?`Forecast: ${pct(a*c/10000)} chance of the event by the deadline (able to do it × choose it if able).`:'Enter two percentages from 0 to 100.';}
function renderForecasts(){
 const s=F.score(data.forecasts),count=s.resolved,summary=count?`${count} scored · mean Brier ${brier(s.overall.brier)}`:`${s.pending} pending`; $('op-f-summary').textContent=summary;
 const calibration=s.bins.filter(b=>b.n).map(b=>`<li>${Math.round(b.lo*100)}–${Math.round(b.hi*100)}% forecasts: ${b.n} cases · predicted ${pct(b.meanP)} · happened ${pct(b.rate)}</li>`).join('');
 const rows=data.forecasts.slice().reverse().map(f=>`<li class="op-f-record"><div><strong>${esc(f.opp)} · ${esc(f.event)} · ${pct(f.p)}</strong> within ${f.turns} own turn${f.turns===1?'':'s'} <small>${esc(f.createdAt.slice(0,16).replace('T',' '))}</small></div><p>${esc(f.detail||'Any '+f.event.toLowerCase())}</p><p class="op-caption">Can pay ${pct(f.pAfford)} · chooses if able ${pct(f.pChoose)} · ${esc(f.evidence||'No evidence entered')}</p><p class="op-caption">Original prediction locked. ${f.res.outcome==='pending'?'Waiting for deadline.':`Outcome: ${esc(f.res.outcome)}${f.res.outcome==='yes'||f.res.outcome==='no'?` · Brier ${brier((f.p-(f.res.outcome==='yes'?1:0))**2)}`:''}`}</p>${f.res.outcome==='pending'?`<div class="op-f-resolve"><label>At deadline<select data-f-outcome="${esc(f.id)}"><option value="pending">Pending</option><option value="yes">Happened</option><option value="no">Did not happen</option><option value="void">Void / could not judge</option></select></label><label>Could pay?<select data-f-afford="${esc(f.id)}"><option value="unknown">Unknown</option><option value="yes">Yes</option><option value="no">No</option></select></label><label>Resolution note<input data-f-note="${esc(f.id)}" placeholder="What was observed?" maxlength="300"></label><button class="cl-button" data-f-resolve="${esc(f.id)}">Record outcome</button></div>`:''}</li>`).join('');
 $('op-f-log').innerHTML=`<p class="op-caption">${s.pending} pending · ${s.excluded} void · ${count} scored. ${count?s.enough?'Calibration is descriptive; compare bins only with their sample counts.':'Few resolved forecasts: the score and bins are descriptive, not evidence of skill.':'Score appears after a yes or no resolution.'} Pending and void never count as no.</p>${count?`<p><strong>Brier ${brier(s.overall.brier)}</strong> over ${count} scored forecast${count===1?'':'s'} (lower is better). Capability: ${s.afford?.n||0} known outcomes; conditional choice: ${s.choose?.n||0} known cases.</p><ul>${calibration}</ul>`:''}<ol class="op-f-list">${rows||'<li>No numerical forecasts yet.</li>'}</ol>`;
 host.querySelectorAll('[data-f-resolve]').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.fResolve,i=data.forecasts.findIndex(f=>f.id===id),field=key=>[...host.querySelectorAll(`[data-f-${key}]`)].find(el=>el.dataset['f'+key[0].toUpperCase()+key.slice(1)]===id),outcome=field('outcome').value,afford=field('afford').value,note=field('note').value;if(outcome==='pending')return;btn.disabled=true;try{data.forecasts[i]=onForecastResolve?await onForecastResolve(id,{outcome,afford,note}):F.resolveForecast(data.forecasts[i],{outcome,afford,note});if(onForecastResolve)onForecastLocal?.(JSON.parse(JSON.stringify(data)));else save();renderForecasts();}catch(e){$('op-f-error').textContent=e.message;btn.disabled=false;}});
}
function select(i,focusId){data.selected=i;save();render();const el=focusId?$(focusId):host.querySelector('[data-analyze="'+i+'"]');el?.focus({preventScroll:true});}
function bind(){
 $('opp-cover').onclick=()=>{covered=!covered;render();$('opp-cover').focus();};
 host.querySelectorAll('[data-prod]').forEach(input=>input.onchange=()=>{data.people[data.selected].prod[+input.dataset.prod]=input.value;save();modelReading();});
 ['op-f-event','op-f-rolls'].forEach(id=>$(id).addEventListener('change',modelReading));
 ['op-f-afford','op-f-choose'].forEach(id=>$(id).addEventListener('input',combined));
 $('op-f-save').onclick=async()=>{const button=$('op-f-save');button.disabled=true;try{if($('op-f-afford').value===''||$('op-f-choose').value==='')throw Error('Enter both probability judgments.');const input={opp:data.people[data.selected].name,event:$('op-f-event').value,detail:$('op-f-detail').value,turns:$('op-f-turns').value,rolls:$('op-f-rolls').value,pAfford:Number($('op-f-afford').value)/100,pChoose:Number($('op-f-choose').value)/100,evidence:$('op-f-evidence').value,model:modelReading()};const f=onForecastCreate?await onForecastCreate(input):F.makeForecast(input);data.forecasts=F.enforceImmutable(data.forecasts,[...data.forecasts,f]);if(onForecastCreate)onForecastLocal?.(JSON.parse(JSON.stringify(data)));else save();$('op-f-error').textContent='';renderForecasts();$('op-f-log').parentElement.open=true;}catch(e){$('op-f-error').textContent=e.message;}finally{button.disabled=false;}};
 host.querySelectorAll('[data-analyze]').forEach(b=>b.onclick=()=>select(+b.dataset.analyze));
 host.querySelectorAll('input[type=number]').forEach(input=>input.addEventListener('focus',()=>input.select()));
 host.querySelectorAll('[data-person]').forEach(input=>input.addEventListener('input',()=>{const p=data.people[+input.dataset.person];if(input.dataset.kind)p[input.dataset.kind][+input.dataset.resource]=num(input.value);else if(input.dataset.field==='total')p.total=input.value===''?null:num(input.value);else p[input.dataset.field]=input.value;refresh();save();}));
 host.querySelectorAll('[data-strategy]').forEach(input=>input.addEventListener(input.tagName==='SELECT'?'change':'input',()=>{data.people[data.selected][input.dataset.strategy]=input.value;refresh();save();}));
 $('opp-selected').onchange=()=>select(+$('opp-selected').value,'opp-selected');
 const remember=()=>{form={event:$('opp-event').value,resource:$('opp-resource').value,quantity:$('opp-quantity').value};};
 $('opp-event').onchange=()=>{syncEventForm();remember();};$('opp-resource').onchange=remember;$('opp-quantity').oninput=remember;
 $('opp-apply').onclick=()=>{remember();try{const p=data.people[data.selected];data.people[data.selected]=applyEvent(p,{type:form.event,q:form.quantity,resource:+form.resource},M.costs);const last=data.people[data.selected].events.at(-1).replace(' · revise guesses','');done=`${p.name}: ${last}. Estimate cleared.`;save();render();$('opp-apply').focus();done='';}catch(error){$('opp-event-done').textContent='';$('opp-event-error').textContent=error.message;}};
 $('opp-predict').onclick=()=>{const p=data.people[data.selected],err=$('opp-predict-error');const missing=[['move','exact move'],['evidence','evidence'],['falsifier','what would change your mind']].filter(([key])=>!p[key].trim()).map(([,l])=>l);if(missing.length){err.className='op-msg cl-warn';err.textContent=`Add the ${missing.join(', ')} first.`;return;}data.predictions.push({name:p.name,text:$('opp-thesis').textContent,at:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),outcome:'pending'});save();err.className='op-msg op-done';err.textContent='Saved. Mark the outcome in the log after their move.';renderPredictions();$('opp-prediction-log').parentElement.open=true;};
 $('opp-check-recall').onclick=()=>{let correct=0,total=0;const lines=data.people.map((p,i)=>{const score=$('opp-recall-score-'+i);if(p.total===null){score.textContent='—';return `<li>${esc(p.name)}: no hand was recorded.</li>`;}let n=0;[...p.known,p.total].forEach((value,j)=>{const input=$('opp-recall-'+i+'-'+j),ok=input.value!==''&&+input.value===value;total++;if(ok){correct++;n++;}input.classList.toggle('op-wrong',!ok);input.classList.toggle('op-right',ok);});score.textContent=`${n}/6`;return `<li>${esc(p.name)}: ${n}/6. Recorded ${p.known.map((v,j)=>`${v} ${resourceNames[j].toLowerCase()}`).join(', ')}; hand ${p.total}.</li>`;});$('opp-recall-result').innerHTML=`<p class="op-recall-total"><strong>${correct}/${total}</strong> facts correct</p><ul class="op-recall-lines">${lines.join('')}</ul>`;};
}
function renderPredictions(){const outcomes=[['pending','Pending'],['yes','Happened'],['no','Did not happen'],['unclear','Unclear / changed']];const rows=data.predictions.map((p,i)=>`<li class="op-pred op-pred-${p.outcome}"><div class="op-pred-meta">${esc(p.at)} · ${esc(p.name)}</div><div class="op-pred-text">${esc(p.text)}</div><div class="op-pred-outcome"><select data-outcome="${i}" aria-label="Prediction ${i+1} outcome">${outcomes.map(([v,l])=>`<option value="${v}" ${p.outcome===v?'selected':''}>${l}</option>`).join('')}</select></div></li>`).reverse().join('');const yes=data.predictions.filter(p=>p.outcome==='yes').length,no=data.predictions.filter(p=>p.outcome==='no').length,pending=data.predictions.filter(p=>p.outcome==='pending').length;$('opp-log-summary').textContent=data.predictions.length?`${pending} pending · ${yes+no} reviewed`:'empty';$('opp-prediction-log').innerHTML=`<p class="op-caption">${yes+no?`${yes}/${yes+no}`:'No'} resolved written predictions marked “happened” by you. Pending and unclear are excluded; this is your own review, not a verified accuracy score. Newest first.</p><ol class="op-preds">${rows||'<li class="op-caption">No predictions yet.</li>'}</ol>`;host.querySelectorAll('[data-outcome]').forEach(input=>input.onchange=()=>{data.predictions[+input.dataset.outcome].outcome=input.value;save();renderPredictions();host.querySelector('[data-outcome="'+input.dataset.outcome+'"]').focus();});}
render();return {restore(raw){const next=sanitize(raw);if(JSON.stringify(next)===JSON.stringify(data))return;data=next;render();},openForecast(){if(covered){covered=false;render();}const section=host.querySelector('.op-forecast');section?.scrollIntoView({block:'start'});host.querySelector('#op-f-event')?.focus({preventScroll:true});},setActive(){}};
}
const api={sanitize,knowledge,possible,applyEvent,emptyOpponent,init};if(typeof module==='object'&&module.exports)module.exports=api;else global.CatanOpponents=api;
})(typeof window!=='undefined'?window:globalThis);
