(function(global){
'use strict';
const names=['Wood','Brick','Sheep','Wheat','Ore'];
const pips=n=>6-Math.abs(7-n);
const categories=['Ore / wheat / sheep','Wood / brick expansion','Resource + matching port','Broad production'];
// Each mini-position is independent; these are not six sites on one shared board.
const profiles=[
 {id:'ows-a',category:0,port:-1,sites:[{units:1,tiles:[[4,6],[3,5],[2,9]]},{units:1,tiles:[[4,10],[3,4],[0,11]]}],why:'Ore and wheat lead; sheep supports dev cards. No brick production makes untraded road expansion awkward.'},
 {id:'exp-a',category:1,port:-1,sites:[{units:1,tiles:[[0,6],[1,5],[2,4]]},{units:1,tiles:[[0,9],[1,10],[3,3]]}],why:'Wood and brick dominate. Wheat is thin and ore absent; expansion is the natural production fit.'},
 {id:'sheep-port',category:2,port:2,sites:[{units:2,tiles:[[2,6],[3,5],[0,10]]},{units:1,tiles:[[2,9],[2,4]]}],why:'Very high sheep production plus the matching 2:1 port. Ore and brick must be imported or traded for.'},
 {id:'broad-a',category:3,port:-1,sites:[{units:1,tiles:[[0,6],[1,9],[3,4]]},{units:1,tiles:[[4,8],[2,5],[3,11]]}],why:'All five resources have meaningful production. Wheat has two numbers; no single recipe family dominates.'},
 {id:'ore-port',category:2,port:4,sites:[{units:2,tiles:[[4,8],[3,9],[2,4]]},{units:1,tiles:[[4,5],[0,3]]}],why:'A city drives ore production and an ore port converts its surplus. Brick is absent.'},
 {id:'ows-b',category:0,port:-1,sites:[{units:2,tiles:[[3,8],[4,5],[2,10]]},{units:1,tiles:[[4,9],[3,11],[1,12]]}],why:'The city supplies wheat, ore and sheep; more ore arrives on 9. Wood is absent; brick production is very weak.'},
 {id:'exp-b',category:1,port:-1,sites:[{units:2,tiles:[[1,8],[0,9],[3,10]]},{units:1,tiles:[[0,5],[2,3],[4,12]]}],why:'Wood and brick dominate; ore exists only on 12. Expansion is favored by production, but intent is not certain.'},
 {id:'broad-b',category:3,port:5,sites:[{units:1,tiles:[[2,8],[1,5],[4,10]]},{units:1,tiles:[[3,6],[0,9]]}],why:'All five resources have useful numbers plus a generic 3:1 port. Production is broad rather than specialized.'}
];
function facts(profile){const weights=[0,0,0,0,0],rolls={};for(const site of profile.sites)for(const [r,n] of site.tiles){weights[r]+=pips(n)*site.units;rolls[n]=(rolls[n]||0)+site.units;}const best=Math.max(...weights),burst=Math.max(...Object.values(rolls));return {weights,strongest:weights.map((v,i)=>v===best?i:-1).filter(i=>i>=0),missing:weights.map((v,i)=>v===0?i:-1).filter(i=>i>=0),rolls,bursts:Object.keys(rolls).map(Number).filter(n=>rolls[n]===burst),burst,port:profile.port};}
function dedupe(hands){return [...new Map(hands.map(h=>[h.join(','),h])).values()];}
function update(hands,event){let next=[];if(event.kind==='delta')next=hands.map(h=>h.map((v,i)=>v+event.delta[i])).filter(h=>h.every(v=>v>=0));else if(event.kind==='loss'){for(const h of hands)for(let i=0;i<5;i++)if(h[i]>0){const a=[...h];a[i]--;next.push(a);}}else if(event.kind==='gain'){for(const h of hands)for(let i=0;i<5;i++){const a=[...h];a[i]++;next.push(a);}}else throw Error('Unknown event');return dedupe(next);}
function summarize(hands){if(!hands.length)throw Error('No consistent hands');return {min:names.map((_,i)=>Math.min(...hands.map(h=>h[i]))),max:names.map((_,i)=>Math.max(...hands.map(h=>h[i]))),totals:[...new Set(hands.map(h=>h.reduce((a,b)=>a+b,0)))],count:hands.length};}
function threat(hands,cost){const n=hands.filter(h=>h.every((v,i)=>v>=cost[i])).length;return n===0?'no':n===hands.length?'yes':'maybe';}
const templates=[
 {id:'public-city',label:'All public events',initial:[2,2,1,1,0],target:'City',events:[{kind:'delta',delta:[0,0,0,0,2],text:'An ore hex pays them 2 ore.'},{kind:'delta',delta:[-1,-1,0,0,0],text:'They pay for a road: −1 wood, −1 brick.'},{kind:'delta',delta:[-1,-1,-1,-1,0],text:'They pay for a settlement: −1 wood, −1 brick, −1 sheep, −1 wheat.'},{kind:'delta',delta:[0,0,0,2,0],text:'Their production pays 2 wheat.'},{kind:'delta',delta:[0,0,0,0,1],text:'Their production pays 1 ore.'}],lesson:'Public gains and recipe payments determine exact counts when you know the starting hand.'},
 {id:'uncertain-city',label:'One hidden loss',initial:[0,1,1,1,2],target:'City',events:[{kind:'delta',delta:[0,0,0,0,1],text:'An ore hex pays them 1 ore.'},{kind:'delta',delta:[0,0,-1,1,0],text:'They trade 1 sheep away for 1 wheat. Both cards are public.'},{kind:'loss',text:'Another player uses a knight and steals 1 card from them. You do not see its type.'}],lesson:'Keep all resource types that could have been stolen. A hand can still support a city in some possibilities, but not all.'},
 {id:'inference-road',label:'A purchase resolves part of the uncertainty',initial:[1,1,0,1,2],target:'Road',events:[{kind:'delta',delta:[0,0,0,0,1],text:'Their production pays 1 ore.'},{kind:'loss',text:'Another player uses a knight and steals 1 unseen card from them.'},{kind:'delta',delta:[0,0,0,1,0],text:'Their production pays 1 wheat.'},{kind:'delta',delta:[0,0,0,-2,-3],text:'They pay for a city: −2 wheat and −3 ore.'},{kind:'delta',delta:[0,0,1,0,0],text:'Their production pays 1 sheep.'}],lesson:'An observed payment eliminates hands that could not afford it. Resource ranges are linked: separately possible wood and brick need not coexist.'},
 {id:'unknown-gain',label:'A hidden card does not erase known cards',initial:[0,0,1,1,1],target:'City',events:[{kind:'delta',delta:[1,1,0,0,0],text:'A roll pays them 1 wood and 1 brick.'},{kind:'delta',delta:[0,0,-1,-1,-1],text:'They buy a development card: −1 sheep, −1 wheat, −1 ore.'},{kind:'gain',text:'They use an older knight to steal 1 card from another player. You do not see its type.'},{kind:'delta',delta:[-1,-1,0,0,0],text:'They pay for a road: −1 wood and −1 brick.'},{kind:'delta',delta:[0,0,0,2,3],text:'One roll pays them 2 wheat and 3 ore from their holdings.'}],lesson:'Their unknown card is additional to the resources you can prove they own. If every consistent hand pays the recipe, the purchase is definitely affordable.'}
];
function makeHand(index,extras=[0,0,0,0,0]){const template=templates[index],initial=template.initial.map((v,i)=>v+extras[i]);let worlds=[initial];const history=[worlds];for(const e of template.events){worlds=update(worlds,e);if(!worlds.length)throw Error('Impossible drill');history.push(worlds);}return {...template,initial,history,worlds};}
const api={names,pips,categories,profiles,facts,update,summarize,threat,templates,makeHand};if(typeof module==='object'&&module.exports)module.exports=api;else global.CatanPracticeModel=api;
})(typeof window!=='undefined'?window:globalThis);
