(function(global){
'use strict';
// Board geometry: three pointy-top hexes whose shared corner sits at (0,0), where the settlement or city stands.
const R=30,SQ3=Math.sqrt(3),CENTERS=[[0,-R],[SQ3*R/2,R/2],[-SQ3*R/2,R/2]];
const SETTLEMENT='M-6.5 6V-1.5L0-7.5L6.5-1.5V6Z',CITY='M-10 6.5V-1H-2.5V-5.5L2.5-10.5L7.5-5.5V6.5Z';
const STAGES={setup:['Study','Recall','Review'],hand:['Memorize','Follow events','Recall','Review'],odds:['Judge','Review']};
function init({root,initial,onSave}){
 const P=global.CatanPracticeModel,M=global.CatanMath,host=root.querySelector('#practice-ui'),$=id=>host.querySelector('#'+id);const names=['Red','Blue','Orange'];
 let prefs={mode:'setup',count:3,seconds:20,level:'mixed',correct:0,total:0,rounds:0,odds:{correct:0,total:0,byType:{}},...(initial||{})};let round=null,timer=null,active=false;
 const save=()=>onSave({...prefs});const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const select=(id,options,label,hint='')=>`<label class="pr-field"><span>${label}${hint?` <small>${hint}</small>`:''}</span><select id="${id}"><option value="">Choose…</option>${options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>`;
 const chips=(id,options,label,extra='')=>`<fieldset class="cl-chips pr-chips ${extra}"><legend>${label}</legend>${options.map(([v,l])=>`<label><input type="checkbox" name="${id}" value="${v}"><span>${l}</span></label>`).join('')}</fieldset>`;
 const answers=id=>[...host.querySelectorAll(`input[name="${id}"]:checked`)].map(x=>x.value).sort();
 const same=(a,b)=>JSON.stringify([...a].map(String).sort())===JSON.stringify([...b].map(String).sort());
 const cueResource=p=>p.category===0?4:p.category===1?0:p.category===2?p.port:3;
 const cueNumbers=p=>[...new Set(p.sites.flatMap(s=>s.tiles.filter(t=>t[0]===cueResource(p)).map(t=>t[1])))];
 const portName=n=>n===-1?'No port':n===5?'Generic 3:1':P.names[n]+' 2:1';
 const listed=(values,fmt=v=>v)=>values.length?values.map(v=>v==='none'?'none':fmt(v)).join(', '):'—';
 const swatch=i=>`<i class="pr-swatch" style="--tile:var(--cl-r${i+1})"></i>`;
 const who=i=>`<i class="pr-dot pr-p${i}"></i>${names[i]}`;
 const costText=cost=>cost.map((n,i)=>n?`${n} ${P.names[i]}`:'').filter(Boolean).join(' + ');
 function stop(){clearInterval(timer);timer=null;}
 function startClock(){stop();if(!active||round?.phase!=='study'||prefs.mode!=='setup'||round.left===0)return;timer=setInterval(()=>{if(document.hidden)return;round.left--;$('practice-clock').textContent=`${round.left}s left`;if(round.left<=0){stop();round.phase='recall';renderRound();}},1000);}
 function shell(){host.innerHTML=`<div class="pr-head"><div><h2>Practice</h2><p class="pr-lede">Read an opponent’s position, hold it in memory, and update it as the game moves.</p></div><span id="practice-score" class="pr-score"></span></div>
<details id="practice-settings" class="pr-settings-panel" open><summary>Drill settings</summary><div class="pr-settings"><label class="pr-drill">Drill<select id="practice-mode"><option value="setup">Setup recall</option><option value="hand">Track a hand through events</option><option value="odds">Odds and timing</option></select></label><label data-for="setup">Opponents<select id="practice-count"><option value="1">One</option><option value="3">Three</option></select></label><label data-for="setup">Study time<select id="practice-seconds"><option value="0">Self-paced</option><option value="10">10 seconds</option><option value="20">20 seconds</option><option value="30">30 seconds</option></select></label><label data-for="hand">Events<select id="practice-level"><option value="mixed">Include hidden steals</option><option value="public">Public events only</option></select></label><button class="cl-button pr-primary" id="practice-new">New drill</button></div></details>
<div class="pr-status"><ol id="practice-stages" class="pr-stages" aria-label="Drill stages"></ol><span id="practice-clock" aria-live="off"></span></div>
<div id="practice-round"></div>
<details class="pr-guide"><summary>Use this at a real table</summary><ol class="cl-facts"><li><strong>Encode once:</strong> player → strongest resource → two key number/resource links → missing resource → port.</li><li><strong>Update on events:</strong> add public income, subtract known build costs, mark uncertainty after hidden steals.</li><li><strong>Ask what changed:</strong> can they now build a city or settlement, race a road, or buy development cards? Separate “can afford” from “will choose.”</li><li><strong>Predict precisely:</strong> action + location + prerequisite + deadline + evidence. Name an alternative and what would prove you wrong.</li><li><strong>Check yourself:</strong> on the Opponents tab, cover the hands you recorded, recall them, and compare.</li></ol><div class="cl-equation">Possible hands after a public change Δ:<br>H′ = {h + Δ : h ∈ H, h + Δ ≥ 0}<br>After one hidden loss: union of h − eᵢ for every possible held resource i.</div><p class="cl-caption">The hand drill keeps the complete set of possible hands, including correlations between resources. Live notes on the Opponents tab keep simpler conservative minimums and an unknown pool. “Possible” is not a probability; guesses are never graded against an unknowable true hand.</p></details>`;
 $('practice-mode').value=prefs.mode;$('practice-count').value=prefs.count;$('practice-seconds').value=prefs.seconds;$('practice-level').value=prefs.level;
 $('practice-mode').onchange=()=>{stop();prefs.mode=$('practice-mode').value;round=null;save();shell();};
 $('practice-count').onchange=()=>{prefs.count=+$('practice-count').value;save();};$('practice-seconds').onchange=()=>{prefs.seconds=+$('practice-seconds').value;save();};$('practice-level').onchange=()=>{prefs.level=$('practice-level').value;save();};
 host.querySelectorAll('.pr-settings [data-for]').forEach(l=>l.hidden=l.dataset.for!==prefs.mode);
 $('practice-new').onclick=newRound;score();renderRound();
 }
 function score(){$('practice-score').innerHTML=prefs.mode==='odds'?`<strong>${prefs.odds.correct}/${prefs.odds.total}</strong> probability judgments`:prefs.rounds?`<strong>${prefs.correct}/${prefs.total}</strong> facts correct · ${prefs.rounds} drill${prefs.rounds===1?'':'s'}`:'No drills checked yet';}
 function stages(){const at=!round?-1:prefs.mode==='setup'?{study:0,recall:1,review:2}[round.phase]:prefs.mode==='odds'?{judge:0,review:1}[round.phase]:{baseline:0,events:1,recall:2,review:3}[round.phase];$('practice-stages').innerHTML=STAGES[prefs.mode].map((s,j)=>`<li${j===at?' aria-current="step"':''}${j<at?' class="pr-done"':''}>${s}</li>`).join('');}
 function newRound(){stop();if(prefs.mode==='setup'){const pool=[...P.profiles];for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}round={phase:'study',people:pool.slice(0,prefs.count),left:prefs.seconds};}else if(prefs.mode==='odds'){round={phase:'judge',drill:global.CatanOddsDrills.generate()};}else{const idx=prefs.level==='public'?0:1+Math.floor(Math.random()*3),extra=[0,0,0,0,0];extra[Math.floor(Math.random()*5)]=Math.floor(Math.random()*3);round={phase:'baseline',drill:P.makeHand(idx,extra),cursor:-1};}renderRound();$('practice-settings').open=false;startClock();}
 function siteSVG(site,port){
  const hex=(cx,cy)=>[-90,-30,30,90,150,210].map(a=>`${(cx+R*Math.cos(a*Math.PI/180)).toFixed(2)},${(cy+R*Math.sin(a*Math.PI/180)).toFixed(2)}`).join(' ');
  const tiles=site.tiles.map(([r,n],k)=>{const [cx,cy]=CENTERS[k],p=P.pips(n);return `<g style="--tile:var(--cl-r${r+1})"><polygon class="pr-hex" points="${hex(cx,cy)}"/><text class="pr-res" x="${cx+(k===1?3:k===2?-3:0)}" y="${cy-15}">${P.names[r]}</text><circle class="pr-token" cx="${cx}" cy="${cy+3}" r="11.5"/><text class="pr-num${n===6||n===8?' pr-hot':''}" x="${cx}" y="${cy+6.5}">${n}</text>${Array.from({length:p},(_,d)=>`<circle class="pr-pip${n===6||n===8?' pr-hot':''}" cx="${(cx+(d-(p-1)/2)*2.8).toFixed(2)}" cy="${cy+10.5}" r=".9"/>`).join('')}</g>`;});
  const coastal=site.tiles.length<3,[sx,sy]=CENTERS[2];
  const sea=coastal?`<polygon class="pr-sea" points="${hex(sx,sy)}"/>${port>=0?`<text class="pr-port-label" x="${sx}" y="${sy-2}">${port===5?'Any':P.names[port]}</text><text class="pr-port-label" x="${sx}" y="${sy+8}">${port===5?'3:1':'2:1'}</text>`:`<text class="pr-port-label" x="${sx}" y="${sy+3}">Sea</text>`}`:'';
  const kind=site.units===2?'City':'Settlement',label=`${kind} touching ${site.tiles.map(([r,n])=>P.names[r]+' '+n).join(', ')}${coastal?port>=0?', on the '+portName(port)+' port':', on the coast':''}`;
  return `<figure class="pr-site"><svg viewBox="-54 -62 108 110" role="img" aria-label="${label}">${sea}${tiles.join('')}<path class="pr-piece" d="${site.units===2?CITY:SETTLEMENT}"/></svg><figcaption>${kind}</figcaption></figure>`;
 }
 // Only a coastal site (two land hexes) can touch a port, so the port is drawn on that site's sea hex.
 function boardHTML(p){const coast=p.sites.findIndex(s=>s.tiles.length<3);return `<div class="pr-sites">${p.sites.map((s,j)=>siteSVG(s,j===coast?p.port:-1)).join('')}</div><p class="pr-port">Port: <strong>${portName(p.port)}</strong></p>`;}
 function profileHTML(p,i){return `<article class="pr-player"><h3>${who(i)}</h3>${boardHTML(p)}</article>`;}
 function renderRound(){
 const box=$('practice-round');host.classList.toggle('pr-active',Boolean(round));$('practice-clock').textContent='';stages();
 if(prefs.mode==='odds'){
  if(!round){box.innerHTML='<div class="pr-empty"><p>Judge a small Catan situation: correlated production, a deadline, a trade, or a conditional forecast. Each question states its assumptions.</p></div>';return;}
  const d=round.drill;
  if(round.phase==='judge'){box.innerHTML=`<article class="pr-odds"><h3>${esc(d.type[0].toUpperCase()+d.type.slice(1))}</h3><p>${esc(d.prompt)}</p><fieldset><legend>Choose an answer</legend>${d.options.map(([key,label])=>`<label><input type="radio" name="odds-answer" value="${key}"> ${esc(label)}</label>`).join('')}</fieldset><button class="cl-button pr-primary" id="odds-check">Check answer</button><p id="odds-error" role="alert"></p></article>`;$('odds-check').onclick=()=>{const chosen=host.querySelector('input[name="odds-answer"]:checked');if(!chosen){$('odds-error').textContent='Choose an answer first.';return;}const ok=chosen.value===d.correct,by=prefs.odds.byType[d.type]||{correct:0,total:0};prefs.odds.byType[d.type]={correct:by.correct+(ok?1:0),total:by.total+1};prefs.odds.correct+=ok?1:0;prefs.odds.total++;save();round.phase='review';round.chosen=chosen.value;renderRound();score();};return;}
  box.innerHTML=`<article class="pr-odds"><h3>${round.chosen===d.correct?'Correct':'Check the model'}</h3><p>${esc(d.prompt)}</p><p><strong>Answer:</strong> ${esc(d.options.find(([key])=>key===d.correct)[1])}</p><p>${esc(d.explanation)}</p><p class="cl-caption">${prefs.odds.byType[d.type].correct}/${prefs.odds.byType[d.type].total} correct in this question type. These are your exercise results, not calibrated game forecasts.</p><button class="cl-button pr-primary" id="odds-next">Next judgment</button></article>`;$('odds-next').onclick=newRound;return;
 }
 if(!round){box.innerHTML=prefs.mode==='setup'?`<div class="pr-empty"><ol><li>Study each opponent’s two buildings.</li><li>Hide them and recall the facts: strongest resource, missing resources, key numbers and port.</li><li>Check your answers against the boards and a reference reading of each strategy.</li></ol><p class="cl-caption">Each opponent is an independent mini-position, not a site on one shared board.</p></div>`:`<div class="pr-empty"><ol><li>Memorize Red’s known hand.</li><li>Follow events one at a time, updating the hand in your head.</li><li>Give the fewest and most of each resource Red could hold, and whether they can pay for a build.</li></ol><p class="cl-caption">After a hidden steal, several hands stay possible. The drill grades what can be known, not a guess.</p></div>`;return;}
 if(prefs.mode==='setup'){
  if(round.phase==='study'){box.innerHTML=`<p class="pr-hint">For each opponent, chunk: <strong>strongest resource · key numbers · missing resources · port</strong>.</p><div class="pr-players">${round.people.map(profileHTML).join('')}</div><div class="pr-actions"><button id="practice-hide" class="cl-button pr-primary">Hide and recall</button></div>`;$('practice-clock').textContent=round.left?`${round.left}s left`:'Self-paced';$('practice-hide').onclick=()=>{stop();round.phase='recall';renderRound();};return;}
  box.innerHTML=`<div id="practice-recall"><p class="pr-hint">Four facts per opponent are scored. The strategy reading is compared with a reference, not scored.</p><div class="pr-players">${round.people.map((p,i)=>`<article class="pr-player"><h3>${who(i)}</h3>${select('setup-strong-'+i,P.names.map((s,j)=>[j,s]),'Strongest resource','most weighted pips; ties accepted')}${chips('setup-missing-'+i,[...P.names.map((s,j)=>[j,s]),['none','None']],'Resources they do not produce')}${chips('setup-numbers-'+i,[...[2,3,4,5,6,8,9,10,11,12].map(n=>[n,n]),['none','None']],`Which rolls pay them ${P.names[cueResource(p)]}?`,'pr-numbers')}${select('setup-port-'+i,[[-1,'No port'],[5,'Generic 3:1'],...P.names.map((s,j)=>[j,s+' 2:1'])],'Port')}<div class="pr-interpret">${select('setup-engine-'+i,P.categories.map((s,j)=>[j,s]),'Strategy reading','not scored')}</div></article>`).join('')}</div><div class="pr-actions"><button id="practice-grade" class="cl-button pr-primary">Check recall</button></div></div><div id="practice-feedback" aria-live="polite"></div>`;
  bindNone();$('practice-grade').onclick=gradeSetup;
 }else{
  const d=round.drill;
  if(round.phase==='baseline'){box.innerHTML=`<h3 class="pr-task">Memorize Red’s hand</h3><p class="cl-caption">${esc(d.label)}. A known starting point; the events that follow are a constructed exercise, not a complete game.</p><div class="pr-hand">${P.names.map((name,i)=>`<div style="--tile:var(--cl-r${i+1})"><span>${name}</span><strong>${d.initial[i]}</strong></div>`).join('')}</div><p class="pr-hint">${d.initial.reduce((a,b)=>a+b,0)} cards in total. Each event replaces the last on screen, so keep a running count in your head.</p><div class="pr-actions"><button class="cl-button pr-primary" id="hand-begin">Hide hand and start events</button></div>`;$('hand-begin').onclick=()=>{round.phase='events';round.cursor=0;renderRound();};return;}
  if(round.phase==='events'){const last=round.cursor===d.events.length-1;box.innerHTML=`<div class="pr-event-head"><h3 class="pr-task">Event ${round.cursor+1} of ${d.events.length}</h3><span class="pr-held">Red holds <strong>${P.summarize(d.history[round.cursor+1]).totals[0]}</strong> ${P.summarize(d.history[round.cursor+1]).totals[0]===1?'card':'cards'}</span></div><div class="pr-progress" aria-hidden="true">${d.events.map((_,i)=>`<i${i<=round.cursor?' class="pr-on"':''}></i>`).join('')}</div><p class="cl-event-card pr-event">${esc(d.events[round.cursor].text)}</p><p class="cl-caption">Update your mental hand before you continue. A hidden steal creates possibilities; it does not reveal a resource.</p><div class="pr-actions"><button class="cl-button pr-primary" id="hand-next">${last?'Recall the final hand':'Next event'}</button></div>`;$('hand-next').onclick=()=>{if(last)round.phase='recall';else round.cursor++;renderRound();};$('hand-next').focus({preventScroll:true});return;}
  box.innerHTML=`<div id="practice-recall"><h3 class="pr-task">What do you know about Red’s hand now?</h3><p class="cl-caption">For each resource, give the fewest and most cards Red could hold, consistent with every event. If you know a count exactly, enter the same number twice.</p><table class="pr-bounds"><thead><tr><th>Resource</th><th>At least</th><th>At most</th></tr></thead><tbody>${P.names.map((r,i)=>`<tr><th>${swatch(i)}${r}</th><td><input id="hand-min-${i}" type="number" inputmode="numeric" min="0" max="30" aria-label="${r} minimum"></td><td><input id="hand-max-${i}" type="number" inputmode="numeric" min="0" max="30" aria-label="${r} maximum"></td></tr>`).join('')}</tbody></table><div class="pr-threat">${select('hand-threat',[['yes','Definitely: every possible hand can'],['maybe','Possibly: only some possible hands can'],['no','No: no possible hand can']],`Can Red pay for a ${d.target.toLowerCase()} (${costText(M.costs[d.target])}) without trading?`)}</div><div class="pr-actions"><button class="cl-button pr-primary" id="practice-grade">Check bounds and threat</button></div></div><div id="practice-feedback" aria-live="polite"></div>`;$('practice-grade').onclick=gradeHand;
 }
 }
 function bindNone(){host.querySelectorAll('.cl-chips input').forEach(input=>input.onchange=()=>{if(!input.checked)return;host.querySelectorAll(`input[name="${input.name}"]`).forEach(other=>{if(other===input)return;if(input.value==='none'||other.value==='none')other.checked=false;});});}
 function record(correct,total){prefs.correct+=correct;prefs.total+=total;prefs.rounds++;round.phase='review';$('practice-grade').disabled=true;$('practice-recall').hidden=true;save();score();stages();$('practice-next').onclick=newRound;const head=$('practice-result');head.tabIndex=-1;head.focus();}
 const resultHTML=(correct,total,extra='')=>`<div class="pr-result" id="practice-result"><div><strong>${correct}/${total}</strong> facts correct${extra}</div><button class="cl-button pr-primary" id="practice-next">Next drill</button></div>`;
 const check=(ok,label,answer,yours)=>`<li class="${ok?'pr-ok':'pr-miss'}"><span class="pr-mark" aria-hidden="true">${ok?'✓':'✗'}</span><span><span class="pr-sr">${ok?'Correct. ':'Missed. '}</span><strong>${label}:</strong> ${answer}${ok?'':` <span class="pr-you">You: ${yours}</span>`}</span></li>`;
 function gradeSetup(){if(round.phase==='review')return;let correct=0;const feedback=round.people.map((p,i)=>{const f=P.facts(p),strong=$('setup-strong-'+i).value,port=$('setup-port-'+i).value,missing=answers('setup-missing-'+i),numbers=answers('setup-numbers-'+i),cue=cueNumbers(p);const checks=[strong!==''&&f.strongest.includes(+strong),port!==''&&+port===f.port,same(missing,f.missing.length?f.missing:['none']),same(numbers,cue.length?cue:['none'])];const n=checks.filter(Boolean).length;correct+=n;const category=$('setup-engine-'+i).value;return `<article class="pr-player pr-review"><h3>${who(i)} <span class="pr-count">${n}/4</span></h3>${boardHTML(p)}<ul class="pr-checks">${check(checks[0],'Strongest',`${f.strongest.map(j=>P.names[j]).join(' / ')} <small>pips ${P.names.map((r,j)=>`${r} ${f.weights[j]}`).join(' · ')}</small>`,strong===''?'—':P.names[+strong])}${check(checks[2],'Not produced',f.missing.map(j=>P.names[j]).join(', ')||'none',listed(missing,v=>P.names[+v]))}${check(checks[3],`Rolls that pay ${P.names[cueResource(p)]}`,cue.join(', ')||'none',listed([...numbers].sort((a,b)=>a-b)))}${check(checks[1],'Port',portName(f.port),port===''?'—':portName(+port))}</ul><p class="pr-reading"><strong>Strategy reading:</strong> ${P.categories[p.category]}. ${category===''?'':+category===p.category?'Yours matches. ':`Yours: ${P.categories[+category]}. `}${p.why}</p></article>`;}).join('');$('practice-feedback').innerHTML=`${resultHTML(correct,round.people.length*4)}<div class="pr-players">${feedback}</div>`;record(correct,round.people.length*4);}
 function gradeHand(){if(round.phase==='review')return;const d=round.drill,s=P.summarize(d.worlds),t=P.threat(d.worlds,M.costs[d.target]);let correct=0;const rows=P.names.map((name,i)=>{const got={};let c=0;for(const kind of ['min','max']){const input=$('hand-'+kind+'-'+i);got[kind]=input.value===''?'—':+input.value;if(input.value!==''&&+input.value===s[kind][i]){correct++;c++;}}return `<tr class="${c===2?'pr-ok':'pr-miss'}"><th>${swatch(i)}${name}</th><td>${s.min[i]}–${s.max[i]}</td><td><span class="pr-mark" aria-hidden="true">${c===2?'✓':'✗'}</span> ${got.min}–${got.max} <small>${c}/2</small></td></tr>`;});const answer=$('hand-threat').value;if(answer===t)correct++;const verdict={yes:'definitely affordable',maybe:'possibly affordable',no:'not affordable'};$('practice-feedback').innerHTML=`${resultHTML(correct,11,` · ${s.count} possible hand${s.count===1?'':'s'}`)}<table class="pr-bounds pr-answer"><thead><tr><th>Resource</th><th>Range</th><th>Yours</th></tr></thead><tbody>${rows.join('')}</tbody></table><ul class="pr-checks">${check(answer===t,`${d.target} (${costText(M.costs[d.target])})`,`${verdict[t]} from the cards alone`,answer?verdict[answer]:'—')}</ul><p class="pr-reading">Total hand: ${s.totals.join(' or ')} cards. ${d.lesson} Ranges are per resource; you cannot combine every maximum into one hand.</p><details class="pr-replay"><summary>Replay the reasoning</summary><ol><li>Start: ${P.names.map((r,j)=>`${r} ${d.initial[j]}`).join(' · ')}.</li>${d.events.map((e,i)=>{const f=P.summarize(d.history[i+1]);return `<li>${esc(e.text)}<br><span class="cl-caption">${P.names.map((r,j)=>`${r} ${f.min[j]}–${f.max[j]}`).join(' · ')} (${f.count} possible hand${f.count===1?'':'s'})</span></li>`;}).join('')}</ol></details>`;record(correct,11);}
 shell();return {setActive(value){active=value;if(!active)stop();else startClock();},openOdds(){stop();prefs.mode='odds';round=null;save();shell();newRound();host.querySelector('#practice-round')?.scrollIntoView({block:'start'});},restore(raw){if(!raw||JSON.stringify(raw)===JSON.stringify(prefs))return;stop();prefs={...prefs,...raw};round=null;shell();}};
}
global.CatanPracticeUI={init};
})(window);
