import express from 'express';
import {oauthRoutes,agentConnectionRoutes} from './lib/oauth.mjs';
import { authRoutes } from './lib/auth-routes.mjs';
import { identity,sameOrigin } from './lib/session.mjs';
import { getReviews,saveReview } from './lib/reviews.mjs';
import { saveState,createForecast,resolveForecast,listForecasts } from './lib/state.mjs';
import { renderPage } from './lib/pages.mjs';
import {fileURLToPath} from 'node:url';
import {mcpRoutes} from './lib/mcp.mjs';
import {dashboardRoutes} from './lib/dashboard-routes.mjs';
import {renderDashboard} from './lib/dashboard-page.mjs';
import {gameRoutes} from './lib/game-routes.mjs';
import {timedGameIdentity} from './lib/game-timing.mjs';
import {gameMcpRoutes} from './lib/game-mcp.mjs';
import {gameObserverRoutes} from './lib/game-observer.mjs';
import {renderGame} from './lib/game-page.mjs';
import {directorRoutes} from './lib/game-director.mjs';
import {renderDirector} from './lib/director-page.mjs';
import {historyRoutes} from './lib/game-history.mjs';
import {renderHistory} from './lib/history-page.mjs';
import {renderPractice} from './lib/practice-page.mjs';
import {renderTrain} from './lib/train-page.mjs';
const app=express();
app.disable('x-powered-by');
app.use((req,res,next)=>{res.set({'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY'});next();});
app.use(express.urlencoded({extended:false,limit:'8kb'}));
app.use(express.json({limit:'320kb'}));
authRoutes(app);
oauthRoutes(app);
mcpRoutes(app);
gameMcpRoutes(app);
gameObserverRoutes(app);
app.use('/dashboard-assets',express.static(fileURLToPath(new URL('./public',import.meta.url))));
const configuredContact=process.env.PRIVACY_CONTACT_EMAIL||'';
const privacyContact=/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(configuredContact)?`<a href="mailto:${configuredContact}">${configuredContact}</a>`:'the operator through the support method published with this deployment';
app.get('/privacy',(req,res)=>res.type('html').send(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Privacy · Catan field guide</title><style>body{max-width:660px;margin:60px auto;padding:0 24px;background:#faf9f6;color:#252522;font:16px/1.7 system-ui}a{color:inherit}h1{line-height:1.2}</style><main><a href="/signin">Catan field guide</a><h1>Privacy</h1><p>Google sign-in provides your account identifier, email address, name and profile picture to authenticate you. This app does not request access to your Gmail, Drive, contacts or calendar.</p><p>The app stores your flashcard review history, dashboard pages and components, and saved guide state, including opponent notes and forecasts you enter, in your account. If you connect an AI agent through the account connection (MCP), you authorize it to read and change your dashboard and to manage your games with full access to their state, including every player's hand, development cards and the deck order, and to read and edit your match history and notes; you can disconnect it from the dashboard. Games are saved to your account. Each player-agent connection can see and play only its assigned seat. A separate read-only sidekick connection can see the public game and your own hand, and can read saved game events; it cannot make moves. Connection tokens can be replaced or revoked from the game. Match history keeps a private copy of each game's complete state after every move and edit made since history recording began, plus the notes, bookmarks, predictions and locked decision-practice attempts you add. It is kept while the game exists in your account and is deleted with it; we do not promise to keep it indefinitely. Replays show your own view unless you choose full information. Account data is stored using Supabase; the site is hosted on Vercel. Authentication cookies keep you signed in. Your saved records are restricted to your account by database access policies.</p><p>Signing out ends your session; it does not delete your saved work. To request deletion of your account and saved data, or ask a privacy question, contact ${privacyContact}.</p><p>Updated September 22, 2026.</p></main></html>`));
app.use(async(req,res,next)=>{
 const {user,supabase}=await timedGameIdentity(req,res,identity);
 if(!user)return req.path.startsWith('/api/')?res.status(401).json({error:'Please sign in again.'}):res.redirect(303,'/signin?next='+encodeURIComponent(req.originalUrl));
 req.user=user;req.supabase=supabase;
 if(!['GET','HEAD'].includes(req.method)&&!sameOrigin(req))return res.sendStatus(403);
 next();
});
agentConnectionRoutes(app);
dashboardRoutes(app);
gameRoutes(app);
directorRoutes(app);
historyRoutes(app);
app.get(['/game','/game/:id'],renderGame);
app.get('/game-tools',renderDirector);
app.get(['/history','/history/:id'],renderHistory);
app.get('/practice/:id',renderPractice);
app.get('/train',renderTrain);
app.get(['/dashboard','/dashboard/:id'],renderDashboard);
app.get('/api/reviews',getReviews);
app.post('/api/reviews',saveReview);
app.post('/api/state',saveState);
app.get('/api/forecasts',listForecasts);
app.post('/api/forecasts',createForecast);
app.post('/api/forecasts/:id/resolve',resolveForecast);
app.get(['/','/guide','/index.html','/flashcards','/flashcards.html'],renderPage);
app.use((req,res)=>res.status(404).send('Page not found.'));
app.use((error,req,res,next)=>res.status(error.status||503).send('The page could not load. Please refresh and try again.'));
export default app;
